module.exports = {
	css:{
    src:[
      'Assests/css/bootstrap.min.css',
      'Assests/font-awesome/css/font-awesome.css',
      'Assests/js/plugins/gritter/jquery.gritter.css',
      'Assests/css/plugins/toastr/toastr.min.css',
      'Assests/css/animate.css',
      'Assests/css/style.css',
      'Assests/css/plugins/datapicker/datepicker3.css',
      'Assests/css/jqueryui.css',
      'Assests/css/plugins/iCheck/custom.css',
      'Assests/css/plugins/morris/morris-0.4.3.min.css'
    ],
    dest:'dist/app.main.css'
  },  
  customcss:{
    src:[
      'Assests/css/your_style.css'
    ],
    dest:'dist/your_style.css'
  },
  js:{
    src:[
      'Assests/js/jquery-2.1.1.js',
      'Assests/js/bootstrap.min.js',
      'Assests/js/plugins/metisMenu/jquery.metisMenu.js',
      'Assests/js/plugins/iCheck/icheck.min.js',
      'Assests/js/boot.js',
      'Assests/js/plugins/toastr/toastr.min.js',
      'Assests/js/plugins/datapicker/bootstrap-datepicker.js',
      'Assests/js/plugins/gritter/jquery.gritter.min.js',
      'Assests/js/plugins/slimscroll/jquery.slimscroll.min.js',
      'Assests/js/plugins/flot/jquery.flot.js',
      'Assests/js/plugins/flot/jquery.flot.tooltip.min.js',
      'Assests/js/plugins/flot/jquery.flot.spline.js',
      'Assests/js/plugins/flot/jquery.flot.resize.js',
      'Assests/js/plugins/flot/jquery.flot.pie.js',
      'Assests/js/plugins/flot/jquery.flot.symbol.js',
      'Assests/js/plugins/flot/curvedLines.js',
      'Assests/js/plugins/peity/jquery.peity.min.js',
      'Assests/js/plugins/pace/pace.min.js',     
      'Assests/js/plugins/jquery-ui/jquery-ui.min.js',
      'Assests/js/plugins/jvectormap/jquery-jvectormap-2.0.2.min.js',
      'Assests/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js',
      'Assests/js/plugins/sparkline/jquery.sparkline.min.js',
      'Assests/js/plugins/chartJs/Chart.min.js',
      'Assests/js/inspinia.js',
      'Assests/js/demo/peity-demo.js',
      'Assests/js/demo/sparkline-demo.js',
      'node_modules/angular/angular.min.js',
      'node_modules/angular-new-router/dist/router.es5.min.js',
      'components/**/*.js',
      'index.js'
      //'app.js',
      //'Scripts/**/*.js',
    ],
    dest:'dist/app.src.js'
  }
}
